package com.wantai.oa.test.dalgen;

import org.mybatis.generator.api.CommentGenerator;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.api.dom.java.InnerEnum;
import org.mybatis.generator.api.dom.java.JavaElement;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;

import java.util.Properties;

/**
 * Created by mapingmp on 16/1/25.
 */
public class CustomerCommentGenerator implements CommentGenerator {
    @Override
    public void addConfigurationProperties(Properties properties) {

    }

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable,
                                IntrospectedColumn introspectedColumn) {
        field.addJavaDocLine(String.format("/* %s(%d)-%s */", introspectedColumn.getJdbcTypeName(),
            introspectedColumn.getLength(), introspectedColumn.getRemarks()));
    }

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable) {
    }

    @Override
    public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable) {
        innerClass.addJavaDocLine(String.format(
            "/**\n" + " * 工资服务实现类\n" + " *\n" + " * @author maping.mp\n"
                    + " * @version $Id: %s.java, v 0.1 2015-1-04 下午10:55:39 maping.mp Exp $\n"
                    + " */", innerClass.getType().getShortName()));
        innerClass.addAnnotation("@Service");
    }

    public void addModelClassComment(InnerClass innerClass, IntrospectedTable introspectedTable) {
        innerClass.addJavaDocLine(String.format(
            "/**\n" + " * 工资服务实现类\n" + " *\n" + " * @author maping.mp\n"
                    + " * @version $Id: %s.java, v 0.1 2015-1-04 下午10:55:39 maping.mp Exp $\n"
                    + " */", innerClass.getType().getShortName()));
        innerClass.addAnnotation("@Service");
    }

    protected void addJavadocTag(JavaElement javaElement, boolean markAsDoNotDelete) {
        javaElement.addJavaDocLine(" *");
        StringBuilder sb = new StringBuilder();
        sb.append(" * ");
        sb.append("@mbggenerated");
        if (markAsDoNotDelete) {
            sb.append(" do_not_delete_during_merge");
        }
        javaElement.addJavaDocLine(sb.toString());
    }

    @Override
    public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable,
                                boolean b) {

        innerClass.addJavaDocLine(String.format(
            "/**\n" + " * 工资服务实现类\n" + " *\n" + " * @author maping.mp\n"
                    + " * @version $Id: %s.java, v 0.1 2015-1-04 下午10:55:39 maping.mp Exp $\n"
                    + " */", innerClass.getType().getShortName()));
        innerClass.addAnnotation("@Service");

        StringBuilder sb = new StringBuilder();
        innerClass.addJavaDocLine("/**");
        innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
        sb.append(" * This class corresponds to the database table ");
        sb.append(introspectedTable.getFullyQualifiedTable());
        innerClass.addJavaDocLine(sb.toString());
        this.addJavadocTag(innerClass, false);
        innerClass.addJavaDocLine(" */");

    }

    @Override
    public void addEnumComment(InnerEnum innerEnum, IntrospectedTable introspectedTable) {

    }

    @Override
    public void addGetterComment(Method method, IntrospectedTable introspectedTable,
                                 IntrospectedColumn introspectedColumn) {
        method.addJavaDocLine(String.format("/* getter of attribute %s */",
            introspectedColumn.getJavaProperty()));
    }

    @Override
    public void addSetterComment(Method method, IntrospectedTable introspectedTable,
                                 IntrospectedColumn introspectedColumn) {
        method.addJavaDocLine(String.format("/* setter of attribute %s */",
            introspectedColumn.getJavaProperty()));
    }

    @Override
    public void addGeneralMethodComment(Method method, IntrospectedTable introspectedTable) {
    }

    @Override
    public void addJavaFileComment(CompilationUnit compilationUnit) {
        compilationUnit.addFileCommentLine("/**\n" + " * Wantai.com Inc.\n"
                                           + " * Copyright (c) 2004-2012 All Rights Reserved.\n"
                                           + " */");
    }

    @Override
    public void addComment(XmlElement xmlElement) {
        xmlElement.addElement(new TextElement("<!-- all have -->"));
    }

    @Override
    public void addRootComment(XmlElement xmlElement) {

    }
}
