--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.337.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016-01-17 18:00:09
-- Server version: 5.6.23-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001016', '整车', '厂家排产', 2, 17, 'true', '厂家排产', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001017', '整车', '底盘下线', 2, 18, 'true', '底盘下线', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001018', '整车', '在途改装厂', 2, 19, 'true', '在途改装厂', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001019', '整车', '改装待上线', 2, 20, 'true', '改装待上线', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001020', '整车', '改装上线', 2, 21, 'true', '改装上线', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001021', '整车', '改装下线', 2, 22, 'true', '改装下线', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001022', '整车', '在途中转库', 2, 23, 'true', '在途中转库', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001023', '整车', '还车验收', 2, 24, 'true', '还车验收', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001024', '整车', '拆装恢复提醒', 2, 25, 'true', '拆装恢复提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001025', '整车', '库存上限预警', 2, 26, 'true', '库存上限预警', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001026', '整车', '库存下限预警', 2, 27, 'true', '库存下限预警', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001027', '整车', '超期车提醒', 2, 28, 'true', '超期车提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001028', '整车', '超期车占比提醒', 2, 29, 'true', '超期车占比提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '200000000000', '20001029', '整车', '合格证有效期提醒', 2, 30, 'true', '合格证有效期提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '300000000000', '30001006', '维修', '索赔上报超时提醒', 3, 7, 'true', '索赔上报超时提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '300000000000', '30001007', '维修', '赔偿不足提醒', 3, 8, 'true', '赔偿不足提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '300000000000', '30001008', '维修', '超期维修提醒', 3, 9, 'true', '超期维修提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '300000000000', '30001009', '维修', '维修订单提醒', 3, 10, 'true', '维修订单提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001011', '配件', '库存上限预警', 4, 12, 'true', '库存上限预警', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001012', '配件', '库存下限预警', 4, 13, 'true', '库存下限预警', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001013', '配件', '配件入库', 4, 14, 'true', '配件入库', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001014', '配件', '3~6月积压件占比提醒', 4, 15, 'true', '3~6月积压件占比提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001015', '配件', '6~12月积压件占比提醒', 4, 16, 'true', '6~12月积压件占比提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001016', '配件', '12~24月积压件占比提醒', 4, 17, 'true', '12~24月积压件占比提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001017', '配件', '24月以上积压件占比提醒', 4, 18, 'true', '24月以上积压件占比提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001018', '配件', '差异库提醒', 4, 19, 'true', '差异库提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '400000000000', '40001019', '配件', '配件销售订单提醒', 4, 20, 'true', '配件销售订单提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '500000000000', '50001002', '牌证', '年检到期提醒', 5, 3, 'true', '年检到期提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '500000000000', '50001003', '牌证', '牌证有效期提醒', 5, 4, 'true', '牌证有效期提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '600000000000', '60001013', '车贷', 'GPS安装提醒', 6, 14, 'true', 'GPS安装提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '600000000000', '60001014', '车贷', '客户还款提醒', 6, 15, 'true', '客户还款提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '600000000000', '60001015', '车贷', '银行还款提醒', 6, 16, 'true', '银行还款提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '600000000000', '60001016', '车贷', '催收提醒', 6, 17, 'true', '催收提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '900000000000', '90001003', '预算', '订单提醒', 9, 4, 'true', '订单提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '700000000000', '70001003', '挂靠', '挂靠订单提醒', 7, 4, 'true', '挂靠订单提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'TYSZ', '800000000000', '80001008', '保险', '到期提醒', 8, 9, 'true', '到期提醒', 'system', 'system');




INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001000', '整车', '采购订单审批', 2, 1, 'true', '采购订单审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001001', '整车', '采购上装审批', 2, 2, 'true', '采购上装审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001002', '整车', '销售定车审批', 2, 3, 'true', '销售定车审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001003', '整车', '销售合同上传', 2, 4, 'true', '销售合同上传', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001004', '整车', '销售车辆交接', 2, 5, 'true', '销售车辆交接', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001005', '整车', '整车拆装审批', 2, 6, 'true', '整车拆装审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001006', '整车', '拆装恢复审批', 2, 7, 'true', '拆装恢复审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001007', '整车', '整车借车审批', 2, 8, 'true', '整车借车审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001008', '整车', '整车还车审批', 2, 9, 'true', '整车还车审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001009', '整车', '合格证变更审批', 2, 10, 'true', '合格证变更审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001010', '整车', '合格证变更完结审批', 2, 11, 'true', '合格证变更完结审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001011', '整车', '整车改装审批', 2, 12, 'true', '整车改装审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001012', '整车', '整车改装完成审批', 2, 13, 'true', '整车改装完成审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001013', '整车', '厂家实销审批', 2, 14, 'true', '厂家实销审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001014', '整车', '库存下限预警', 2, 15, 'true', '库存下限预警', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '200000000000', '20001015', '整车', '整车销售订单（电商）', 2, 16, 'true', '整车销售订单（电商）', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '300000000000', '30001000', '维修', '外出维修审批', 3, 1, 'true', '外出维修审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '300000000000', '30001001', '维修', '外出维修完成审批', 3, 2, 'true', '外出维修完成审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '300000000000', '30001002', '维修', '厂家赔付审批', 3, 3, 'true', '厂家赔付审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '300000000000', '30001003', '维修', '索赔上报超时提醒', 3, 4, 'true', '索赔上报超时提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '300000000000', '30001004', '维修', '超期维修提醒', 3, 5, 'true', '超期维修提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '300000000000', '30001005', '维修', '维修订单提醒（电商）', 3, 6, 'true', '维修订单提醒（电商）', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001000', '配件', '配件销售退货审批', 4, 1, 'true', '配件销售退货审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001001', '配件', '配件调拨审批', 4, 2, 'true', '配件调拨审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001002', '配件', '配件采购审批', 4, 3, 'true', '配件采购审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001003', '配件', '采购入库审批', 4, 4, 'true', '采购入库审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001004', '配件', '配件外采审批', 4, 5, 'true', '配件外采审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001005', '配件', '配件盘点审批', 4, 6, 'true', '配件盘点审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001006', '配件', '配件损溢审批', 4, 7, 'true', '配件损溢审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001007', '配件', '配件调价审批', 4, 8, 'true', '配件调价审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001008', '配件', '库存下限预警', 4, 9, 'true', '库存下限预警', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001009', '配件', '差异库提醒', 4, 10, 'true', '差异库提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '400000000000', '40001010', '配件', '配件销售订单（电商）', 4, 11, 'true', '配件销售订单（电商）', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '500000000000', '50001000', '牌证', '牌证缴款审批', 5, 1, 'true', '牌证缴款审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '500000000000', '50001001', '牌证', '牌证信息审批', 5, 2, 'true', '牌证信息审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001000', '车贷', '短借放贷审批', 6, 1, 'true', '短借放贷审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001001', '车贷', '短借抵押手续审批', 6, 2, 'true', '短借抵押手续审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001002', '车贷', '按揭放贷审批', 6, 3, 'true', '按揭放贷审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001003', '车贷', '按揭提车审批', 6, 4, 'true', '按揭提车审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001004', '车贷', '按揭GPS审批', 6, 5, 'true', '按揭GPS审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001005', '车贷', '按揭手续交接审批', 6, 6, 'true', '按揭手续交接审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001006', '车贷', '银行放贷审批', 6, 7, 'true', '银行放贷审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001007', '车贷', '清收措施审批', 6, 8, 'true', '清收措施审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001008', '车贷', '清收抵押物处理审批', 6, 9, 'true', '清收抵押物处理审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001009', '车贷', '清收抵押物处理结果审批', 6, 10, 'true', '清收抵押物处理结果审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001010', '车贷', '清收结果审批', 6, 11, 'true', '清收结果审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001011', '车贷', 'GPS安装审批', 6, 12, 'true', 'GPS安装审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '600000000000', '60001012', '车贷', '银行还款提醒', 6, 13, 'true', '银行还款提醒', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '900000000000', '90001000', '预算', '订单申请（电商）', 9, 1, 'true', '订单申请（电商）', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '900000000000', '90001001', '预算', '预算订单审批', 9, 2, 'true', '预算订单审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '900000000000', '90001002', '预算', '预算调查审批', 9, 3, 'true', '预算调查审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '700000000000', '70001000', '挂靠', '挂靠审批', 7, 1, 'true', '挂靠审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '700000000000', '70001001', '挂靠', '挂靠完结审批', 7, 2, 'true', '挂靠完结审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '700000000000', '70001002', '挂靠', '挂靠订单提醒（电商）', 7, 3, 'true', '挂靠订单提醒（电商）', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001000', '保险', '保险审批', 8, 1, 'true', '保险审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001001', '保险', '保险完结审批', 8, 2, 'true', '保险完结审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001002', '保险', '理赔处理措施审批', 8, 3, 'true', '理赔处理措施审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001003', '保险', '理赔小案结案审批', 8, 4, 'true', '理赔小案结案审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001004', '保险', '理赔现场勘查审批', 8, 5, 'true', '理赔现场勘查审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001005', '保险', '理赔诉讼审批', 8, 6, 'true', '理赔诉讼审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001006', '保险', '理赔结果审批', 8, 7, 'true', '理赔结果审批', 'system', 'system');
INSERT INTO oa_business_config(company_code, company_id, config_type, biz_item, biz_event, biz_item_name, biz_event_name, biz_item_order, biz_event_order, enable, memo, operator, last_modified_oeprator) VALUES
('99999999999', 1, 'DBSZ', '800000000000', '80001007', '保险', '理赔审批', 8, 8, 'true', '理赔审批', 'system', 'system');


